name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # 也更新到 v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libavfilter-dev \
          libswscale-dev \
          libpostproc-dev \
          libswresample-dev \
          libx264-dev \
          libfdk-aac-dev \
          libbz2-dev \
          zlib1g-dev

    - name: Build Release
      run: |
        cd src
        chmod +x Buildit
        ./Buildit Release 2>&1 | tee build.log
        
    - name: Debug build outputs
      run: |
        echo "=== Directory structure ==="
        find . -type d
        
        echo "=== Build outputs ==="
        find . -name "*.so" -o -name "*.a"
        
        echo "=== Build directories ==="
        find . -type d -name "build" -o -name "dist"

    - name: Collect artifacts
      run: |
        echo "Creating artifacts directory..."
        mkdir -p artifacts/lib
        mkdir -p artifacts/include
        mkdir -p artifacts/logs
        
        # 复制构建日志
        if [ -f src/build.log ]; then
          cp src/build.log artifacts/logs/
        fi
        
        # 复制编译产物
        find . -name "*.so" -exec cp -v {} artifacts/lib/ \;
        find . -name "*.a" -exec cp -v {} artifacts/lib/ \;
        find . -name "*.h" -exec cp -v {} artifacts/include/ \;
        
        # 生成构建信息
        {
          echo "Build timestamp: $(date)"
          echo "Git commit: $(git rev-parse HEAD)"
          echo "Git branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Build platform: $(uname -a)"
          echo "Compiler version: $(gcc --version | head -n1)"
        } > artifacts/build-info.txt
        
        echo "=== Artifacts contents ==="
        ls -R artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # 更新到 v4
      with:
        name: build-outputs
        path: artifacts/
        compression-level: 9  # v4 新特性：最大压缩级别
        retention-days: 90    # v4 新特性：保留天数
