name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # ... 前面的步骤保持不变 ...

    - name: Collect and upload artifacts
      if: always()
      run: |
        echo "Creating artifacts directory..."
        mkdir -p artifacts
        
        echo "Finding and copying build outputs..."
        # 复制所有的 .so 文件
        find src -name "*.so" -exec cp {} artifacts/ \;
        # 复制所有的 .a 文件
        find src -name "*.a" -exec cp {} artifacts/ \;
        
        echo "Artifacts directory contents:"
        ls -la artifacts/

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: artifacts/
        
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          src/*.log
          src/nbproject/*.log
          src/build/*.log
