name: Build x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-x64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # 安装开发库
        sudo apt-get install -y \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libavfilter-dev \
          libswscale-dev \
          libpostproc-dev \
          libswresample-dev \
          libx264-dev \
          libfdk-aac-dev \
          libbz2-dev \
          zlib1g-dev

    - name: Build x64
      run: |
        cd src  # 切换到src目录
        chmod +x Buildit
        ./Buildit x64
        
    - name: List build artifacts
      run: |
        cd src  # 切换到src目录
        ls -R dist/

    - name: Upload x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: x64-build
        path: |
          src/dist/x64/GNU-Linux/
          src/dist/x64/
