name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libavfilter-dev \
          libswscale-dev \
          libpostproc-dev \
          libswresample-dev \
          libx264-dev \
          libfdk-aac-dev \
          libbz2-dev \
          zlib1g-dev

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "src directory contents:"
        ls -la src/
        echo "src/nbproject contents:"
        ls -la src/nbproject/

    - name: Build Release
      run: |
        cd src
        chmod +x Buildit
        ./Buildit Release
        
    - name: List build artifacts
      run: |
        cd src
        ls -R dist/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: |
          src/dist/Release/GNU-Linux/
          src/dist/Release/
